# W.A.P to prompt a user to enter his/her name and mailing address and display the entered information on the screen 
name = input("Enter your name :") 
addrs1 = input("Enter your Line 1 :")
addrs2 = input("Enter your Line 2 :")
addrs3 = input("Enter your Line 3 :")
city = input("Enter your city :")
state = input("Enter your state :")
pin = input("Enter your PIN :")
print(name)
print("Adress:")
print(addrs1,',')
print(addrs2,',')
print(addrs3,',')
print(city,'-',pin)
print(state)